# Generated by Django 5.0.6 on 2024-05-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionário',
            new_name='Funcionario',
        ),
    ]
