# Generated by Django 5.0.6 on 2024-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servico_options_alter_funcionario_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo:')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('icone', models.CharField(choices=[('lni-leaf', 'folha'), ('lni-cog', 'engrenagem'), ('lni-rocket', 'foguete'), ('lni-layers', 'camadas'), ('lni-laptop-phone', 'lap-top')], max_length=18, verbose_name='icone')),
                ('descricao', models.CharField(max_length=200, verbose_name='descricao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
